# English titles for IMDb Top 1000 entries listed under their original-language names.
EN = {
 "Gisaengchung": "Parasite", "Soorarai Pottru": "Soorarai Pottru", "Cidade de Deus": "City of God", "Seppuku": "Harakiri",
 "Nuovo Cinema Paradiso": "Cinema Paradiso", "Hotaru no haka": "Grave of the Fireflies", "Oldeuboi": "Oldboy",
 "Mononoke-hime": "Princess Mononoke", "Tengoku to jigoku": "High and Low", "Jagten": "The Hunt",
 "Jodaeiye Nader az Simin": "A Separation", "Babam ve Oglum": "My Father and My Son", "Bacheha-Ye aseman": "Children of Heaven",
 "Idi i smotri": "Come and See", "Ladri di biciclette": "Bicycle Thieves", "M - Eine Stadt sucht einen Mrder": "M",
 "Mandariinid": "Tangerines", "El secreto de sus ojos": "The Secret in Their Eyes", "Hauru no ugoku shiro": "Howl's Moving Castle",
 "Eskiya": "The Bandit", "Dom za vesanje": "Time of the Gypsies", "Tonari no Totoro": "My Neighbor Totoro",
 "Smultronstllet": "Wild Strawberries", "Det sjunde inseglet": "The Seventh Seal", "Du rififi chez les hommes": "Rififi",
 "Koe no katachi": "A Silent Voice", "Contratiempo": "The Invisible Guest", "Relatos salvajes": "Wild Tales", "Kis Uykusu": "Winter Sleep",
 "kami kodomo no Ame to Yuki": "Wolf Children", "Okuribito": "Departures", "Taegukgi hwinalrimyeo": "Tae Guk Gi: The Brotherhood of War",
 "Salinui chueok": "Memories of Murder", "Amores perros": "Amores Perros", "La leggenda del pianista sull'oceano": "The Legend of 1900",
 "Crna macka, beli macor": "Black Cat, White Cat", "Fa yeung nin wah": "In the Mood for Love", "Trois couleurs: Rouge": "Three Colors: Red",
 "Chung Hing sam lam": "Chungking Express", "Kaze no tani no Naushika": "Nausicaä of the Valley of the Wind", "Fanny och Alexander": "Fanny and Alexander",
 "Zerkalo": "Mirror", "Viskningar och rop": "Cries and Whispers", "El ngel exterminador": "The Exterminating Angel", "Ivanovo detstvo": "Ivan's Childhood",
 "Jungfrukllan": "The Virgin Spring", "Kakushi-toride no san-akunin": "The Hidden Fortress", "Kaguyahime no monogatari": "The Tale of the Princess Kaguya",
 "Serbuan maut 2: Berandal": "The Raid 2", "Tropa de Elite 2: O Inimigo Agora  Outro": "Elite Squad 2: The Enemy Within",
 "Darbareye Elly": "About Elly", "Nefes: Vatan Sagolsun": "The Breath", "Vozvrashchenie": "The Return",
 "Bom Yeoareum Gaeul Gyeoul Geurigo Bom": "Spring, Summer, Fall, Winter... and Spring", "Mou gaan dou": "Infernal Affairs",
 "Yeopgijeogin geunyeo": "My Sassy Girl", "Pfekuto bur": "Perfect Blue", "Festen": "The Celebration", "Tenk no shiro Rapyuta": "Castle in the Sky",
 "8": "8½", "Vivre sa vie: Film en douze tableaux": "My Life to Live", "Bronenosets Potemkin": "Battleship Potemkin",
 "Manbiki kazoku": "Shoplifters", "Bir Zamanlar Anadolu'da": "Once Upon a Time in Anatolia", "4 luni, 3 saptmni si 2 zile": "4 Months, 3 Weeks and 2 Days",
 "Gegen die Wand": "Head-On", "Ying xiong": "Hero", "Cowboy Bebop: Tengoku no tobira": "Cowboy Bebop: The Movie", "Nueve reinas": "Nine Queens",
 "Mimi wo sumaseba": "Whisper of the Heart", "Trois couleurs: Bleu": "Three Colors: Blue", "Aguirre, der Zorn Gottes": "Aguirre, the Wrath of God",
 "Forushande": "The Salesman", "Perfetti sconosciuti": "Perfect Strangers", "Kaze tachinu": "The Wind Rises", "La migliore offerta": "The Best Offer",
 "Kokuhaku": "Confessions", "Ajeossi": "The Man from Nowhere", "Madeo": "Mother", "Chugyeokja": "The Chaser",
 "Mn som hatar kvinnor": "The Girl with the Dragon Tattoo", "Druk": "Another Round", "Auf der anderen Seite": "The Edge of Heaven",
 "Ondskan": "Evil", "Diarios de motocicleta": "The Motorcycle Diaries", "Gongdong gyeongbi guyeok JSA": "Joint Security Area",
 "Todo sobre mi madre": "All About My Mother", "Lat sau san taam": "Hard Boiled", "En man som heter Ove": "A Man Called Ove",
 "Gake no ue no Ponyo": "Ponyo", "Papurika": "Paprika", "Efter brylluppet": "After the Wedding", "Zwartboek": "Black Book",
 "Abre los ojos": "Open Your Eyes", "Kurenai no buta": "Porco Rosso", "Spoorloos": "The Vanishing", "Rupan sansei: Kariosutoro no shiro": "The Castle of Cagliostro",
 "Nelyubov": "Loveless", "Leviafan": "Leviathan", "Serbuan maut": "The Raid", "Kari-gurashi no Arietti": "The Secret World of Arrietty",
 "Celda 211": "Cell 211", "Huo Yuan Jia": "Fearless", "Jeux d'enfants": "Love Me If You Dare", "Boksuneun naui geot": "Sympathy for Mr. Vengeance",
 "Batoru rowaiaru": "Battle Royale", "Lola rennt": "Run Lola Run", "Trois couleurs: Blanc": "Three Colors: White", "Omohide poro poro": "Only Yesterday",
 "Sen to Chihiro no kamikakushi": "Spirited Away", "Kimi no na wa.": "Your Name", "Shichinin no samurai": "Seven Samurai", "Rashômon": "Rashomon",
 "Rashmon": "Rashomon", "Yjinb": "Yojimbo", "Il buono, il brutto, il cattivo": "The Good, the Bad and the Ugly",
 "C'era una volta il West": "Once Upon a Time in the West", "La vita  bella": "Life Is Beautiful", "El laberinto del fauno": "Pan's Labyrinth",
 "Le fabuleux destin d'Amlie Poulain": "Amélie", "Das Leben der Anderen": "The Lives of Others", "Der Untergang": "Downfall",
 "Das Boot": "Das Boot", "Majo no takkybin": "Kiki's Delivery Service", "Kumonosu-j": "Throne of Blood", "Taare Zameen Par": "Like Stars on Earth",
 "Les intouchables": "The Intouchables", "Intouchables": "The Intouchables", "Le salaire de la peur": "The Wages of Fear",
 "Les quatre cents coups": "The 400 Blows", "La haine": "Hate", "Le notti di Cabiria": "Nights of Cabiria", "La dolce vita": "La Dolce Vita",
 "Per qualche dollaro in più": "For a Few Dollars More", "Per qualche dollaro in pi": "For a Few Dollars More", "Pather Panchali": "Pather Panchali",
 "Tôkyô monogatari": "Tokyo Story", "Tky monogatari": "Tokyo Story", "Toki o kakeru shjo": "The Girl Who Leapt Through Time",
 "Sennen joy": "Millennium Actress", "Tokyo goddofzazu": "Tokyo Godfathers", "Tokyo Godfathers": "Tokyo Godfathers",
}
import re
def key(s): return re.sub(r'[^a-z0-9]', '', s.lower().replace('\x1a', ''))
EN_K = {key(k): v for k, v in EN.items()}
def english(title):
    return EN_K.get(key(title), title.replace('\x1a', ''))
