# Canonical trait vocabulary: label -> (category, anime tags, steam tags)
# Only whitelisted concepts become traits, which keeps the graph meaningful and family-safe.
V = {
 # ---------- mechanics / gameplay & power systems ----------
 "Open world": ("mechanic", [], ["Open World"]),
 "Crafting": ("mechanic", [], ["Crafting"]),
 "Base building": ("mechanic", [], ["Base-Building"]),
 "City building": ("mechanic", [], ["City Builder"]),
 "Colony sim": ("mechanic", [], ["Colony Sim"]),
 "Automation": ("mechanic", [], ["Automation"]),
 "Survival": ("mechanic", ["survival", "struggle to survive"], ["Survival", "Open World Survival Craft"]),
 "Roguelike runs": ("mechanic", [], ["Rogue-like", "Rogue-lite", "Roguelike", "Action Roguelike", "Traditional Roguelike", "Roguevania"]),
 "Deckbuilding": ("mechanic", [], ["Deckbuilding", "Roguelike Deckbuilder"]),
 "Card battles": ("mechanic", ["card battle"], ["Card Game", "Trading Card Game", "Card Battler"]),
 "Souls-like combat": ("mechanic", [], ["Souls-like"]),
 "Metroidvania": ("mechanic", [], ["Metroidvania"]),
 "Turn-based combat": ("mechanic", [], ["Turn-Based Combat", "Turn-Based", "Turn-based"]),
 "Tactics on a grid": ("mechanic", [], ["Turn-Based Tactics", "Tactical RPG", "Strategy RPG", "Grid-Based Movement"]),
 "Stealth": ("mechanic", [], ["Stealth"]),
 "Hack and slash": ("mechanic", [], ["Hack and Slash", "Character Action Game", "Spectacle fighter"]),
 "Bullet hell": ("mechanic", [], ["Bullet Hell", "Shoot 'Em Up", "Shoot 'em Up"]),
 "Fighting game": ("mechanic", [], ["Fighting", "2D Fighter", "3D Fighter"]),
 "Platforming": ("mechanic", [], ["Platformer", "2D Platformer", "3D Platformer", "Precision Platformer", "Puzzle-Platformer"]),
 "Parkour": ("mechanic", [], ["Parkour"]),
 "Tower defense": ("mechanic", [], ["Tower Defense"]),
 "Real-time strategy": ("mechanic", [], ["RTS", "Real Time Tactics", "Action RTS"]),
 "Grand strategy": ("mechanic", [], ["Grand Strategy", "4X"]),
 "Choices matter": ("mechanic", [], ["Choices Matter", "Multiple Endings", "Choose Your Own Adventure"]),
 "Visual novel": ("mechanic", ["based on a visual novel", "visual novel"], ["Visual Novel"]),
 "Dating sim": ("mechanic", [], ["Dating Sim", "Otome"]),
 "Management sim": ("mechanic", [], ["Management", "Resource Management", "Managerial"]),
 "Life sim": ("mechanic", [], ["Life Sim"]),
 "Physics sandbox": ("mechanic", [], ["Physics", "Destruction"]),
 "Puzzles": ("mechanic", [], ["Puzzle", "Logic"]),
 "Point and click": ("mechanic", [], ["Point & Click", "Point-and-click"]),
 "Hidden objects": ("mechanic", [], ["Hidden Object"]),
 "Escape rooms": ("mechanic", [], ["Escape Room"]),
 "Social deduction": ("mechanic", [], ["Social Deduction"]),
 "Party games": ("mechanic", [], ["Party Game", "Party", "Minigames"]),
 "Idle clicker": ("mechanic", [], ["Clicker", "Idler"]),
 "Hero shooter": ("mechanic", [], ["Hero Shooter", "Class-Based"]),
 "Looter shooter": ("mechanic", [], ["Looter Shooter", "Loot"]),
 "Extraction shooter": ("mechanic", [], ["Extraction Shooter"]),
 "MOBA": ("mechanic", [], ["MOBA"]),
 "MMO worlds": ("mechanic", [], ["MMORPG", "Massively Multiplayer"]),
 "Auto battler": ("mechanic", [], ["Auto Battler"]),
 "Rhythm and music": ("mechanic", ["band", "musical band", "music"], ["Rhythm", "Music"]),
 "Idols": ("mechanic", ["idol", "idols", "idols (female)"], []),
 "Farming": ("mechanic", ["agriculture"], ["Farming Sim", "Farming", "Agriculture"]),
 "Cooking": ("mechanic", ["cooking", "food preparation", "lethal chef"], ["Cooking"]),
 "Fishing": ("mechanic", ["fishing"], ["Fishing"]),
 "Hunting": ("mechanic", [], ["Hunting"]),
 "Racing": ("mechanic", ["racing", "motorsport", "car chases"], ["Racing", "Driving", "Combat Racing", "Offroad", "Automobile Sim"]),
 "Motorcycles": ("icon", ["motorcycles"], ["Motorbike", "Motocross", "Bikes"]),
 "Flying aircraft": ("mechanic", ["aviation", "air combat"], ["Flight", "Jet"]),
 "Creature collecting": ("mechanic", ["gotta catch them all"], ["Creature Collector"]),
 "Hacking": ("mechanic", ["hacking", "hacker"], ["Hacking"]),
 "Time travel": ("story", ["time travel", "time manipulation", "time loop"], ["Time Travel", "Time Manipulation"]),
 "Psychic powers": ("mechanic", ["psi-powers", "extrasensory perception", "telekinesis"], []),
 "Shapeshifting": ("mechanic", ["shapeshifting", "transformations"], []),
 "Summoning": ("mechanic", ["summoning"], []),
 "Magic": ("mechanic", ["magic", "spellcasting", "sorcery", "magic circles"], ["Magic"]),
 "Martial arts": ("mechanic", ["martial arts", "hand to hand combat"], ["Martial Arts", "Beat 'em up"]),
 "Swordplay": ("mechanic", ["swordplay", "swords & co"], ["Swordplay"]),
 "Archery": ("mechanic", ["archery"], ["Archery"]),
 "Gunfights": ("mechanic", ["gunfights"], ["Third-Person Shooter", "Top-Down Shooter", "Twin Stick Shooter"]),
 "Sniping": ("mechanic", ["sniper"], ["Sniper"]),
 "Soccer": ("story", ["football"], ["Football (Soccer)"]),
 "Basketball": ("story", ["basketball"], ["Basketball"]),
 "Baseball": ("story", ["baseball"], ["Baseball"]),
 "Boxing and wrestling": ("story", ["wrestling", "boxing", "combat sport"], ["Boxing", "Wrestling"]),
 "Swimming": ("story", ["swimming"], ["Swimming"]),
 "Board games": ("mechanic", ["strategy game", "shogi", "mahjong", "go"], ["Board Game", "Tabletop"]),
 "Gambling": ("theme", ["gambling"], ["Gambling"]),
 "Sports": ("story", ["sports", "team sports"], ["Sports"]),
 "Noir": ("theme", ["noir"], ["Noir"]),
 # ---------- themes ----------
 "Revenge": ("theme", ["revenge", "violent retribution"], ["Revenge"]),
 "Anti-hero lead": ("theme", ["anti-hero", "antihero", "villain protagonist"], ["Villain Protagonist"]),
 "Found family": ("theme", ["found family"], []),
 "Coming of age": ("theme", ["coming of age"], []),
 "Grief and loss": ("theme", ["death of a loved one", "grief"], ["Emotional"]),
 "Friendship": ("theme", ["friendship", "teamwork"], []),
 "Rebellion": ("theme", ["rebellion", "revolution"], []),
 "Politics": ("theme", ["politics", "political"], ["Politics", "Political", "Political Sim"]),
 "Money and markets": ("theme", ["economics", "money"], ["Economy", "Capitalism", "Trading"]),
 "Conspiracies": ("theme", ["conspiracy", "secret organisation"], ["Conspiracy", "Illuminati"]),
 "Faith and cults": ("theme", ["cult", "religion"], ["Faith"]),
 "Philosophy": ("theme", ["philosophy"], ["Philosophical"]),
 "Psychological twists": ("theme", ["psychological", "psychological drama", "plot twists"], ["Psychological"]),
 "Thriller": ("theme", ["thriller", "suspense"], ["Thriller"]),
 "Detective work": ("theme", ["detective", "detectives", "crime fiction"], ["Detective", "Investigation", "Detective-mystery"]),
 "Mystery": ("theme", ["mystery"], ["Mystery"]),
 "Crime and gangs": ("theme", ["mafia", "yakuza", "organized crime", "gangs"], ["Crime"]),
 "Heists and thieves": ("theme", ["thievery"], ["Heist"]),
 "Assassins": ("trope", ["assassins"], ["Assassin"]),
 "Police": ("trope", ["police", "cops", "policeman", "law and order"], []),
 "Terrorism": ("theme", ["terrorism"], []),
 "Espionage": ("theme", ["espionage"], []),
 "Battle royale": ("story", ["death game", "battle royale"], ["Battle Royale"]),
 "Tournaments": ("story", ["tournament", "tournaments"], []),
 "Amnesia": ("trope", ["amnesia", "memory manipulation"], []),
 "Reincarnation": ("trope", ["reincarnation"], []),
 "Isekai": ("story", ["isekai", "person in a strange world"], []),
 "Trapped in a game world": ("story", ["virtual world", "virtual reality"], []),
 "Body swap": ("trope", ["body swapping"], []),
 "Immortality": ("trope", ["immortality"], []),
 "Clones": ("trope", ["clone"], []),
 "Human experiments": ("theme", ["genetic modification", "human experimentation"], []),
 "Class struggle": ("theme", ["class struggle", "social class issues", "slavery"], []),
 "Dystopia": ("setting", ["dystopian", "dystopia"], ["Dystopian"]),
 "Satire and parody": ("theme", ["parody", "satire", "self-parody"], ["Parody", "Satire"]),
 "Dark humor": ("theme", ["black humour"], ["Dark Humor", "Dark Comedy"]),
 "Surreal": ("theme", ["surreal comedy"], ["Surreal", "Psychedelic"]),
 "Cozy and relaxing": ("theme", ["iyashikei", "iyashi-kei", "heart-warming"], ["Cozy", "Wholesome", "Relaxing"]),
 "Working life": ("theme", ["work", "working life", "workplace", "work life", "occupation and career"], ["Job Simulator"]),
 "Showbiz": ("theme", ["acting", "showbiz", "entertainment industry"], []),
 "Otaku culture": ("theme", ["otaku culture", "otaku"], []),
 "Delinquents": ("trope", ["delinquent", "delinquents"], []),
 "Siblings": ("trope", ["siblings", "sibling yin yang"], []),
 "Twins": ("trope", ["twins"], []),
 "Orphans": ("trope", ["orphan", "orphans"], []),
 "Marriage": ("theme", ["marriage", "arranged marriage"], []),
 # ---------- settings ----------
 "Outer space": ("setting", ["space", "outer space", "space travel", "shipboard", "other planet"], ["Space", "Space Sim", "Spaceships"]),
 "Space battles": ("setting", ["space battles", "space opera"], []),
 "Mars": ("setting", ["mars"], ["Mars"]),
 "Cyberpunk": ("setting", ["cyberpunk"], ["Cyberpunk"]),
 "Steampunk": ("setting", ["steampunk"], ["Steampunk"]),
 "Post-apocalyptic": ("setting", ["post-apocalyptic", "post apocalypse", "apocalyptic fiction", "end of the world"], ["Post-apocalyptic"]),
 "Medieval": ("setting", ["medieval", "middle ages"], ["Medieval"]),
 "Dark fantasy": ("setting", ["dark fantasy"], ["Dark Fantasy"]),
 "Feudal Japan": ("setting", ["feudal japan", "feudal warfare", "samurai"], ["Samurai"]),
 "Ancient China": ("setting", ["ancient china", "wuxia", "cultivation"], ["Wuxia"]),
 "Wild West": ("setting", ["western", "wild west"], ["Western"]),
 "World War II": ("setting", ["world war ii"], ["World War II"]),
 "Military": ("setting", ["military", "special squads", "air force", "navy"], ["Military"]),
 "Tanks": ("icon", ["tanks"], ["Tanks"]),
 "Naval warfare": ("setting", ["ships", "navy"], ["Naval", "Naval Combat"]),
 "Pirates": ("trope", ["pirates"], ["Pirates"]),
 "Sailing": ("setting", ["sailing"], ["Sailing"]),
 "Submarines": ("icon", ["submarine"], ["Submarine"]),
 "Under the sea": ("setting", ["ocean", "mermaid", "underwater"], ["Underwater"]),
 "Trains": ("icon", ["trains"], ["Trains"]),
 "Snowy lands": ("setting", ["snowscape", "winter"], ["Snow"]),
 "Desert": ("setting", ["desert"], ["Desert"]),
 "Dungeon crawling": ("setting", ["dungeon"], ["Dungeon Crawler", "Mystery Dungeon"]),
 "Underground": ("setting", ["underground"], ["Underground"]),
 "Tokyo": ("setting", ["tokyo"], []),
 "America": ("setting", ["united states", "americas"], ["America"]),
 "Countryside": ("setting", ["rural", "countryside"], []),
 "Magic school": ("setting", ["magic school"], []),
 "School clubs": ("setting", ["school club", "school clubs", "club"], []),
 "Prison": ("setting", ["prison"], ["Prison"]),
 "Royal court": ("setting", ["royalty", "royal affairs", "nobility", "aristocracy", "nobleman"], []),
 "Afterlife": ("setting", ["afterlife", "spirit realm"], []),
 # ---------- tropes & creatures ----------
 "Zombies": ("trope", ["zombie", "undead"], ["Zombies"]),
 "Vampires": ("trope", ["vampire", "vampires"], ["Vampire"]),
 "Werewolves": ("trope", ["werewolf", "werewolves"], ["Werewolves"]),
 "Demons": ("trope", ["demon", "demons"], ["Demons"]),
 "Ghosts": ("trope", ["ghost", "ghost stories"], []),
 "Yokai and folklore": ("trope", ["youkai", "japanese mythology", "folklore"], []),
 "Mythology and gods": ("trope", ["mythology", "greek mythology", "gods", "deity"], ["Mythology"]),
 "Vikings": ("trope", ["vikings", "norse mythology"], ["Vikings"]),
 "Angels": ("trope", ["angels", "angel"], []),
 "Dragons": ("trope", ["dragons", "dragon"], ["Dragons"]),
 "Dinosaurs": ("trope", ["dinosaurs"], ["Dinosaurs"]),
 "Elves": ("trope", ["elf"], []),
 "Dwarves": ("trope", ["dwarf"], ["Dwarf"]),
 "Goblins": ("trope", ["goblin"], []),
 "Knights": ("trope", ["knight"], []),
 "Witches": ("trope", ["witch"], []),
 "Magical girls": ("trope", ["magical girl", "mahou shoujo", "henshin"], []),
 "Robots and androids": ("trope", ["robot", "robots", "android", "androids", "robots & android", "robot helper"], ["Robots"]),
 "Giant mechs": ("icon", ["mecha", "piloted robot", "super robot", "real robot", "super robots", "real robots", "power suit"], ["Mechs"]),
 "Artificial intelligence": ("trope", ["artificial intelligence"], ["Artificial Intelligence"]),
 "Cyborgs": ("trope", ["cyborg", "cyborgs", "human enhancement", "bionic powers"], ["Transhumanism"]),
 "Aliens": ("trope", ["aliens", "alien", "humanoid alien", "alien invasion"], ["Aliens"]),
 "Kaiju": ("trope", ["kaiju", "daikaijuu"], []),
 "Superheroes": ("trope", ["superhero", "superheroes"], ["Superhero"]),
 "Superpowers": ("trope", ["super power", "superpowers"], []),
 "Ninjas": ("trope", ["ninja"], ["Ninja"]),
 "Exorcists and curses": ("trope", ["exorcism", "curse", "curses"], []),
 "Cosmic horror": ("trope", ["cosmic horror"], ["Lovecraftian"]),
 "Body horror": ("trope", ["body horror"], []),
 "Psychological horror": ("theme", [], ["Psychological Horror"]),
 "Survival horror": ("theme", [], ["Survival Horror"]),
 "Horror": ("theme", ["horror"], ["Horror"]),
 "Gore": ("theme", ["gore", "splatter & gore", "excessive violence"], ["Gore", "Blood"]),
 "Cats": ("icon", ["cats"], ["Cats"]),
 "Dogs": ("icon", ["dogs"], ["Dog"]),
 "Horses": ("icon", ["horses"], ["Horses"]),
 "Bounty hunters": ("trope", ["bounty hunter"], []),
 "Beastfolk": ("trope", ["beastman", "juujin", "kemonomimi"], []),
 "Tokusatsu heroes": ("trope", ["tokusatsu"], []),
 "Crossovers": ("icon", ["crossover"], []),
}
# Tags that exclude a title entirely (keep the game family-safe)
BLOCK_ANIME = {"hentai", "pornography", "borderline porn", "erotic game", "sexual abuse", "rape", "incest", "loli", "adult audience only", "based on an eroge"}
BLOCK_STEAM = {"Hentai", "NSFW"}
NON_GAME_STEAM = {"Utilities", "Software", "Design & Illustration", "Game Development", "Animation & Modeling",
                  "Audio Production", "Video Production", "Photo Editing", "Web Publishing", "Software Training", "Movie"}

# ---------- merge in the new connector traits ----------
from connectors import C as _C
TMDB_EXTRA = {}   # tmdb keyword -> trait
for _lab, (_cat, _an, _st, _tm, _rx) in _C.items():
    if _lab in V:
        cat0, an0, st0 = V[_lab]; V[_lab] = (cat0, list(dict.fromkeys(an0 + _an)), list(dict.fromkeys(st0 + _st)))
    else:
        V[_lab] = (_cat, _an, _st)
    for _k in _tm: TMDB_EXTRA.setdefault(_k, _lab)
# tournaments get movie keywords and text patterns too
TMDB_EXTRA.setdefault("tournament", "Tournaments"); TMDB_EXTRA.setdefault("competition", "Tournaments")
